dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: osx
    - os: linux
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
        - sudo apt-get install --no-install-recommends -y rpm

cache:
  directories:
    - node_modules

install:
  - npm uninstall hexo --save
  - npm install
  - npm install hexo --save

script:
  - npm run electron:build

branches:
  only:
    - master
